# Generated by Django 5.1.6 on 2025-03-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_superuser_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
