# Generated by Django 5.1.6 on 2025-03-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_following_count'),
        ('users', '0005_create_users_groups'),
    ]

    operations = [
    ]
