# Generated by Django 5.1.6 on 2025-03-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20250305_1047'),
        ('users', '0007_create_user_permissions_table'),
    ]

    operations = [
    ]
