# Generated by Django 5.1.6 on 2025-03-05 15:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20250305_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_user_permissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='user_user_permissions',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='User_groups',
        ),
        migrations.DeleteModel(
            name='User_user_permissions',
        ),
    ]
